dist: xenial

language: python
matrix:
  include:
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7

services:
  - docker

addons:
  sonarcloud:
    organization: maxbrunet-github
    token:
      secure: 2H8Xu2tDpeWtTGoxvMHaWfz8Uc16FSyPT+8kJHM0FSJhAgt1lI6vh8MlGDtQlNfG95HMQ1LhidNfu2re/QEiFpnDofaAQWQR0WdrnJjrsFTltwRDbfe0kgEitC9FC3E5Y/JPWDey5VHOxeJtdApXwloWKwbsN0Ww5zdF+Z25ZsS0bfmevxTaBZsyVNxTJzuX7g8dAlvFRlZU2oyzxODI092WJ+4eb9z0oEXQfyZsqmhQmRFDGDFVcRrLyG4Gut9nxHeaj7IspX3NTclN2ECssIQugfnERiYQN7qygRYzN3Bev69Fb98OJrRBxZYFLArAJOO6MW3PJDOVZwYkYW1kMiOrx7+Mz6CTFmeTw7T3t0IOulsQa/ud75oJFGYliAgqC53KrDICxmOrV1Q/bTqIffV5wOTJXq0JYHKvgkbLH7a9LIPXAvVL4aK/Ww5ba1vsYdw4nlX3PfUFopGtQwUBV66FeXkg30gWH/JzSfaJIVqJdlos6QsTpBKWWyL48vqYaVTdn0Z5lQ/DCohbMvMLHurtTNFcIEGzDMI4JvmfnwYSIVK8pJTlqAqNT9lFJswWLCL6uy2gIGS7TmUubipvA86LwCH9/8P2VALEF+0GP9prfZwZHXQJ0KgSsc7B2Ik3Khei5qEHeOVohQ3ZqJXPZ5BWJuMC7H0aHsCf+GRxdFg=

before_install:
  - tests/scripts/setup-mattermost.sh

install:
  - pip install .

script:
  - python setup.py test --addopts \
      "--cov=src
       --cov-report=xml:coverage-reports/coverage-${TRAVIS_PYTHON_VERSION}.xml
       --black
       --flake8
       --isort"
  - sonar-scanner -Dsonar.projectKey=maxbrunet_mmemoji -Dsonar.sources=.

deploy:
  provider: pypi
  user: maxbrunet
  password:
    secure: h25Z73aqS3t5qTGHU7psnXmG8g2p/BBjjttRycM116/I7KWEame/TwO2scPExzkjNLZiFaWGf2hnc/jJsYI+LmxHlLR9lLK2lQbEehVHeIXuC+5E8vo46aJMTFZHpI9RMAtecGUN1B84IhaXDhDNYLl/jL62HB0HxTwjta6QHeVsJpUPP9IrE3WQq4xgDWzTxWOIK5XTItkFPaTNhuASGQSr3dL+O+Vz84tu7gqRMpIpCw5FWVU4/thm2fq4p5QkL7xHk0FC1Y4wrfZaqhg2Xno8dMtWItUwu69fpJvt+7kd/dqPQnNsjjE7BSLkPKN/i46tJ/jcNMWZ3dgiXqx/d20PmL0xghRaCIfuQ2PXaW9jB0U+TO0VLDntqiqdCx0ZQ8JA99tvUwdbt+PgVV68NMIwTaKh3jpeG72T87l+chpOAQ8v1SNNG1me8PKk1tg4kfJMn7Qy5ckFx2sKyae+zQ4lqRfZZ0One399Dos2/b2Z2QZ9UMRSmkQwpn/hGxZHHqlB76QGUu4AEn8yyDUbDw9bbiEDIlGzUPGi4ytSko9ol+WONZRMKBBxTXUo2KxOikqQrv/AqcFV2bHqzyUHXmK/hWKiVbAANajg2195dHPSxclAnpVorJRR3farInJmIB/ZdYY0PgECL1T6jEpY4c3wTQwKkxAb/GdkYFpqLyg=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.6
